// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/v1/resources/filesystem.proto

package resources

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Filesystem struct {
	Filesystem string `protobuf:"bytes,1,opt,name=filesystem,proto3" json:"filesystem" csv:"filesystem" yaml:"filesystem"`
	Type       string `protobuf:"bytes,2,opt,name=type,proto3" json:"type" csv:"type" yaml:"type"`
	// KB as in 1024 bytes
	SizeKb               uint64   `protobuf:"varint,3,opt,name=size_kb,json=sizeKb,proto3" json:"size_kb" csv:"size_kb" yaml:"size_kb"`
	UsedKb               uint64   `protobuf:"varint,4,opt,name=used_kb,json=usedKb,proto3" json:"used_kb" csv:"used_kb" yaml:"used_kb"`
	FreeKb               uint64   `protobuf:"varint,5,opt,name=free_kb,json=freeKb,proto3" json:"free_kb" csv:"free_kb" yaml:"free_kb"`
	UsedPct              float32  `protobuf:"fixed32,6,opt,name=used_pct,json=usedPct,proto3" json:"used_pct" csv:"used_pct" yaml:"used_pct"`
	Inodes               uint64   `protobuf:"varint,7,opt,name=inodes,proto3" json:"inodes" csv:"inodes" yaml:"inodes"`
	InodesUsed           uint64   `protobuf:"varint,8,opt,name=inodes_used,json=inodesUsed,proto3" json:"inodes_used" csv:"inodes_used" yaml:"inodes_used"`
	InodesFree           uint64   `protobuf:"varint,9,opt,name=inodes_free,json=inodesFree,proto3" json:"inodes_free" csv:"inodes_free" yaml:"inodes_free"`
	InodesUsedPct        float32  `protobuf:"fixed32,10,opt,name=inodes_used_pct,json=inodesUsedPct,proto3" json:"inodes_used_pct" csv:"inodes_used_pct" yaml:"inodes_used_pct"`
	MountedOn            string   `protobuf:"bytes,11,opt,name=mounted_on,json=mountedOn,proto3" json:"mounted_on" csv:"mounted_on" yaml:"mounted_on"`
	MountOptions         []string `protobuf:"bytes,12,rep,name=mount_options,json=mountOptions,proto3" json:"mount_options" csv:"mount_options" yaml:"mount_options"`
	IsLocal              bool     `protobuf:"varint,13,opt,name=is_local,json=isLocal,proto3" json:"is_local" csv:"is_local" yaml:"is_local"`
	IsAutomounted        bool     `protobuf:"varint,14,opt,name=is_automounted,json=isAutomounted,proto3" json:"is_automounted" csv:"is_automounted" yaml:"is_automounted"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" csv:"-" yaml:"-"`
	XXX_unrecognized     []byte   `json:"-" csv:"-" yaml:"-"`
	XXX_sizecache        int32    `json:"-" csv:"-" yaml:"-"`
}

func (m *Filesystem) Reset()         { *m = Filesystem{} }
func (m *Filesystem) String() string { return proto.CompactTextString(m) }
func (*Filesystem) ProtoMessage()    {}
func (*Filesystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e36e7140ee4a547, []int{0}
}

func (m *Filesystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filesystem.Unmarshal(m, b)
}
func (m *Filesystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filesystem.Marshal(b, m, deterministic)
}
func (m *Filesystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filesystem.Merge(m, src)
}
func (m *Filesystem) XXX_Size() int {
	return xxx_messageInfo_Filesystem.Size(m)
}
func (m *Filesystem) XXX_DiscardUnknown() {
	xxx_messageInfo_Filesystem.DiscardUnknown(m)
}

var xxx_messageInfo_Filesystem proto.InternalMessageInfo

func (m *Filesystem) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

func (m *Filesystem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Filesystem) GetSizeKb() uint64 {
	if m != nil {
		return m.SizeKb
	}
	return 0
}

func (m *Filesystem) GetUsedKb() uint64 {
	if m != nil {
		return m.UsedKb
	}
	return 0
}

func (m *Filesystem) GetFreeKb() uint64 {
	if m != nil {
		return m.FreeKb
	}
	return 0
}

func (m *Filesystem) GetUsedPct() float32 {
	if m != nil {
		return m.UsedPct
	}
	return 0
}

func (m *Filesystem) GetInodes() uint64 {
	if m != nil {
		return m.Inodes
	}
	return 0
}

func (m *Filesystem) GetInodesUsed() uint64 {
	if m != nil {
		return m.InodesUsed
	}
	return 0
}

func (m *Filesystem) GetInodesFree() uint64 {
	if m != nil {
		return m.InodesFree
	}
	return 0
}

func (m *Filesystem) GetInodesUsedPct() float32 {
	if m != nil {
		return m.InodesUsedPct
	}
	return 0
}

func (m *Filesystem) GetMountedOn() string {
	if m != nil {
		return m.MountedOn
	}
	return ""
}

func (m *Filesystem) GetMountOptions() []string {
	if m != nil {
		return m.MountOptions
	}
	return nil
}

func (m *Filesystem) GetIsLocal() bool {
	if m != nil {
		return m.IsLocal
	}
	return false
}

func (m *Filesystem) GetIsAutomounted() bool {
	if m != nil {
		return m.IsAutomounted
	}
	return false
}

func init() {
	proto.RegisterType((*Filesystem)(nil), "peekaboo.v1.resources.Filesystem")
}

func init() { proto.RegisterFile("pb/v1/resources/filesystem.proto", fileDescriptor_2e36e7140ee4a547) }

var fileDescriptor_2e36e7140ee4a547 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x4f, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0x49, 0xe6, 0xc4, 0x2f, 0x71, 0x06, 0x82, 0x6d, 0xda, 0x61, 0x9b, 0xd9, 0x58, 0xf1,
	0xa5, 0x36, 0xa1, 0xc7, 0x1e, 0x4a, 0x7a, 0xc8, 0x25, 0x85, 0x14, 0x43, 0x2f, 0xbd, 0x18, 0xcb,
	0x7e, 0x49, 0x45, 0x1c, 0xcb, 0x58, 0x72, 0x20, 0xfd, 0x50, 0xfd, 0x8c, 0x45, 0x52, 0xea, 0x98,
	0xde, 0xde, 0xef, 0xef, 0xf3, 0x9f, 0x07, 0x41, 0xcd, 0xe2, 0xe3, 0x22, 0x6e, 0x50, 0x8a, 0xb6,
	0xc9, 0x51, 0xc6, 0x5b, 0x5e, 0xa2, 0x3c, 0x49, 0x85, 0x87, 0xa8, 0x6e, 0x84, 0x12, 0xe4, 0x5b,
	0x8d, 0xb8, 0xcf, 0x98, 0x10, 0xd1, 0x71, 0x11, 0x75, 0xbe, 0xbf, 0x6f, 0x43, 0x80, 0x55, 0xe7,
	0x25, 0xbf, 0x01, 0x2e, 0x49, 0xea, 0x04, 0x4e, 0xe8, 0x25, 0x3d, 0x86, 0x10, 0x18, 0xa9, 0x53,
	0x8d, 0x74, 0x60, 0x14, 0x33, 0x93, 0x1f, 0x30, 0x96, 0xfc, 0x15, 0xd3, 0x3d, 0xa3, 0xc3, 0xc0,
	0x09, 0x47, 0x89, 0xab, 0xe1, 0x9a, 0x69, 0xa1, 0x95, 0x58, 0x68, 0x61, 0x64, 0x05, 0x0d, 0xad,
	0xb0, 0x6d, 0xd0, 0x24, 0xbe, 0x58, 0x41, 0xc3, 0x35, 0x23, 0x3f, 0x61, 0x62, 0x12, 0x75, 0xae,
	0xa8, 0x1b, 0x38, 0xe1, 0x20, 0x31, 0x0d, 0x8f, 0xb9, 0x22, 0xdf, 0xc1, 0xe5, 0x95, 0x28, 0x50,
	0xd2, 0xb1, 0x8d, 0x58, 0x44, 0xfe, 0xc0, 0xd4, 0x4e, 0xa9, 0x76, 0xd2, 0x89, 0x11, 0xc1, 0x52,
	0x4f, 0x12, 0x8b, 0x9e, 0x41, 0x2f, 0xa1, 0x5e, 0xdf, 0xb0, 0x6a, 0x10, 0xc9, 0x15, 0x7c, 0xed,
	0x35, 0x98, 0xdd, 0x60, 0x76, 0xfb, 0x97, 0x16, 0xfd, 0x04, 0xbf, 0x00, 0x0e, 0xa2, 0xad, 0x14,
	0x16, 0xa9, 0xa8, 0xe8, 0xd4, 0x7c, 0x01, 0xef, 0xcc, 0x6c, 0x2a, 0xf2, 0x0f, 0x7c, 0x03, 0x52,
	0x51, 0x2b, 0x2e, 0x2a, 0x49, 0x67, 0xc1, 0x30, 0xf4, 0x92, 0x99, 0x21, 0x37, 0x96, 0xd3, 0x2f,
	0xc8, 0x65, 0x5a, 0x8a, 0x3c, 0x2b, 0xa9, 0x1f, 0x38, 0xe1, 0x24, 0x19, 0x73, 0xf9, 0xa0, 0x21,
	0xf9, 0x0f, 0x73, 0x2e, 0xd3, 0xac, 0x55, 0xe2, 0xdc, 0x49, 0xe7, 0xc6, 0xe0, 0x73, 0xb9, 0xbc,
	0x90, 0xf7, 0xcb, 0xe7, 0xbb, 0x1d, 0x57, 0x2f, 0x2d, 0x8b, 0x72, 0x71, 0x88, 0x3f, 0x7e, 0xea,
	0x75, 0x99, 0x31, 0xd9, 0xa1, 0xb8, 0xde, 0xef, 0xe2, 0x4f, 0x17, 0x71, 0xdb, 0x4d, 0xcc, 0x35,
	0x17, 0x71, 0xf3, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x36, 0x68, 0x32, 0x35, 0x02, 0x00, 0x00,
}
