// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/v1/resources/group.proto

package resources

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Group struct {
	Groupname string `protobuf:"bytes,1,opt,name=groupname,proto3" json:"groupname" csv:"groupname" yaml:"groupname"`
	Gid       uint64 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid" csv:"gid" yaml:"gid"`
	// Signed GID for Mac OS X.
	GidSigned            int64    `protobuf:"varint,3,opt,name=gid_signed,json=gidSigned,proto3" json:"gid_signed" csv:"gid_signed" yaml:"gid_signed"`
	Members              []string `protobuf:"bytes,4,rep,name=members,proto3" json:"members" csv:"members" yaml:"members"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" csv:"-" yaml:"-"`
	XXX_unrecognized     []byte   `json:"-" csv:"-" yaml:"-"`
	XXX_sizecache        int32    `json:"-" csv:"-" yaml:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dbb673ccab8b80e, []int{0}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

func (m *Group) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *Group) GetGidSigned() int64 {
	if m != nil {
		return m.GidSigned
	}
	return 0
}

func (m *Group) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*Group)(nil), "peekaboo.v1.resources.Group")
}

func init() { proto.RegisterFile("pb/v1/resources/group.proto", fileDescriptor_3dbb673ccab8b80e) }

var fileDescriptor_3dbb673ccab8b80e = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xb1, 0x4b, 0xc5, 0x30,
	0x1c, 0x84, 0x89, 0xa9, 0x4a, 0x32, 0x49, 0x40, 0x08, 0xa8, 0x10, 0x9c, 0xb2, 0x98, 0x50, 0x1c,
	0x1d, 0x44, 0x17, 0xf7, 0xb8, 0xb9, 0x48, 0xd3, 0xfc, 0x88, 0xa1, 0xa6, 0x09, 0x49, 0xdb, 0xbf,
	0xff, 0xd1, 0x42, 0xfb, 0xe0, 0x6d, 0x77, 0xc7, 0x37, 0xdc, 0x47, 0x1f, 0xb2, 0xd5, 0x4b, 0xab,
	0x0b, 0xd4, 0x34, 0x97, 0x1e, 0xaa, 0xf6, 0x25, 0xcd, 0x59, 0xe5, 0x92, 0xa6, 0xc4, 0xee, 0x33,
	0xc0, 0xd0, 0xd9, 0x94, 0xd4, 0xd2, 0xaa, 0x03, 0x79, 0xce, 0xf4, 0xfa, 0x6b, 0xa5, 0xd8, 0x23,
	0x25, 0x1b, 0x3e, 0x76, 0x11, 0x38, 0x12, 0x48, 0x12, 0x73, 0x1e, 0xd8, 0x1d, 0xc5, 0x3e, 0x38,
	0x7e, 0x25, 0x90, 0x6c, 0xcc, 0x1a, 0xd9, 0x13, 0xa5, 0x3e, 0xb8, 0xdf, 0x1a, 0xfc, 0x08, 0x8e,
	0x63, 0x81, 0x24, 0x36, 0xc4, 0x07, 0xf7, 0xbd, 0x0d, 0x8c, 0xd3, 0xdb, 0x08, 0xd1, 0x42, 0xa9,
	0xbc, 0x11, 0x58, 0x12, 0xb3, 0xd7, 0xcf, 0x8f, 0x9f, 0x77, 0x1f, 0xa6, 0xbf, 0xd9, 0xaa, 0x3e,
	0x45, 0xbd, 0xbf, 0x7a, 0xf9, 0xef, 0x6c, 0x3d, 0x9a, 0xce, 0x83, 0xd7, 0x17, 0x36, 0x6f, 0x47,
	0xb2, 0x37, 0x9b, 0xd2, 0xeb, 0x29, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x8e, 0x3d, 0x87, 0xf1, 0x00,
	0x00, 0x00,
}
