// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/v1/resources/user.proto

package resources

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username" csv:"username" yaml:"username"`
	Comment  string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment" csv:"comment" yaml:"comment"`
	Uid      uint64 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid" csv:"uid" yaml:"uid"`
	Gid      uint64 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid" csv:"gid" yaml:"gid"`
	// Signed UID for Mac OS X.
	UidSigned int64 `protobuf:"varint,5,opt,name=uid_signed,json=uidSigned,proto3" json:"uid_signed" csv:"uid_signed" yaml:"uid_signed"`
	// Signed GID for Mac OS X.
	GidSigned            int64    `protobuf:"varint,6,opt,name=gid_signed,json=gidSigned,proto3" json:"gid_signed" csv:"gid_signed" yaml:"gid_signed"`
	Directory            string   `protobuf:"bytes,7,opt,name=directory,proto3" json:"directory" csv:"directory" yaml:"directory"`
	Shell                string   `protobuf:"bytes,8,opt,name=shell,proto3" json:"shell" csv:"shell" yaml:"shell"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" csv:"-" yaml:"-"`
	XXX_unrecognized     []byte   `json:"-" csv:"-" yaml:"-"`
	XXX_sizecache        int32    `json:"-" csv:"-" yaml:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_cefae016e8f0da92, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *User) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *User) GetUidSigned() int64 {
	if m != nil {
		return m.UidSigned
	}
	return 0
}

func (m *User) GetGidSigned() int64 {
	if m != nil {
		return m.GidSigned
	}
	return 0
}

func (m *User) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *User) GetShell() string {
	if m != nil {
		return m.Shell
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "peekaboo.v1.resources.User")
}

func init() { proto.RegisterFile("pb/v1/resources/user.proto", fileDescriptor_cefae016e8f0da92) }

var fileDescriptor_cefae016e8f0da92 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x80, 0x89, 0xed, 0xfe, 0x74, 0x4e, 0x12, 0x14, 0xc2, 0xa2, 0x50, 0x3c, 0xf5, 0x62, 0xc3,
	0xe2, 0xd1, 0x83, 0xe8, 0x23, 0x54, 0xbc, 0x78, 0x91, 0xa6, 0x19, 0xb2, 0x61, 0xdb, 0xa6, 0x24,
	0xcd, 0x82, 0xaf, 0xe9, 0x13, 0x49, 0x52, 0x36, 0x0b, 0x7b, 0x9b, 0xef, 0xfb, 0x06, 0x42, 0x06,
	0x76, 0x93, 0xe0, 0xa7, 0x3d, 0xb7, 0xe8, 0x8c, 0xb7, 0x1d, 0x3a, 0xee, 0x1d, 0xda, 0x7a, 0xb2,
	0x66, 0x36, 0xf4, 0x7e, 0x42, 0x3c, 0xb6, 0xc2, 0x98, 0xfa, 0xb4, 0xaf, 0xd3, 0xc6, 0xd3, 0x1f,
	0x81, 0xfc, 0xcb, 0xa1, 0xa5, 0x3b, 0xd8, 0x86, 0xed, 0xb1, 0x1d, 0x90, 0x91, 0x92, 0x54, 0x45,
	0x93, 0x98, 0x32, 0xd8, 0x74, 0x66, 0x18, 0x70, 0x9c, 0xd9, 0x4d, 0x4c, 0x67, 0xa4, 0xb7, 0x90,
	0x79, 0x2d, 0x59, 0x56, 0x92, 0x2a, 0x6f, 0xc2, 0x18, 0x8c, 0xd2, 0x92, 0xe5, 0x8b, 0x51, 0x5a,
	0xd2, 0x47, 0x00, 0xaf, 0xe5, 0x8f, 0xd3, 0x6a, 0x44, 0xc9, 0x56, 0x25, 0xa9, 0xb2, 0xa6, 0xf0,
	0x5a, 0x7e, 0x46, 0x11, 0xb2, 0xba, 0xe4, 0xf5, 0x92, 0x55, 0xca, 0x0f, 0x50, 0x48, 0x6d, 0xb1,
	0x9b, 0x8d, 0xfd, 0x65, 0x9b, 0xf8, 0xfa, 0x45, 0xd0, 0x3b, 0x58, 0xb9, 0x03, 0xf6, 0x3d, 0xdb,
	0xc6, 0xb2, 0xc0, 0xc7, 0xfb, 0xf7, 0x9b, 0xd2, 0xf3, 0xc1, 0x8b, 0xba, 0x33, 0x03, 0x3f, 0x7f,
	0xfc, 0xb9, 0x6f, 0x85, 0x4b, 0xc4, 0xa7, 0xa3, 0xe2, 0x57, 0xf7, 0x7a, 0x4d, 0x93, 0x58, 0xc7,
	0xab, 0xbd, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x28, 0xeb, 0xed, 0x8f, 0x53, 0x01, 0x00, 0x00,
}
