// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/v1/services/system.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	resources "github.com/peekaboo-labs/peekaboo/pkg/pb/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSystemRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemRequest) Reset()         { *m = GetSystemRequest{} }
func (m *GetSystemRequest) String() string { return proto.CompactTextString(m) }
func (*GetSystemRequest) ProtoMessage()    {}
func (*GetSystemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7735c972877c634, []int{0}
}

func (m *GetSystemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemRequest.Unmarshal(m, b)
}
func (m *GetSystemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemRequest.Marshal(b, m, deterministic)
}
func (m *GetSystemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemRequest.Merge(m, src)
}
func (m *GetSystemRequest) XXX_Size() int {
	return xxx_messageInfo_GetSystemRequest.Size(m)
}
func (m *GetSystemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemRequest proto.InternalMessageInfo

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7735c972877c634, []int{1}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type ListUsersResponse struct {
	Users                []*resources.User `protobuf:"bytes,1,rep,name=users,proto3" json:"users"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7735c972877c634, []int{2}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*resources.User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ListGroupsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()    {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7735c972877c634, []int{3}
}

func (m *ListGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsRequest.Unmarshal(m, b)
}
func (m *ListGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsRequest.Merge(m, src)
}
func (m *ListGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupsRequest.Size(m)
}
func (m *ListGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsRequest proto.InternalMessageInfo

type ListGroupsResponse struct {
	Groups               []*resources.Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7735c972877c634, []int{4}
}

func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(m, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroups() []*resources.Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func init() {
	proto.RegisterType((*GetSystemRequest)(nil), "peekaboo.v1.services.GetSystemRequest")
	proto.RegisterType((*ListUsersRequest)(nil), "peekaboo.v1.services.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "peekaboo.v1.services.ListUsersResponse")
	proto.RegisterType((*ListGroupsRequest)(nil), "peekaboo.v1.services.ListGroupsRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "peekaboo.v1.services.ListGroupsResponse")
}

func init() { proto.RegisterFile("pb/v1/services/system.proto", fileDescriptor_e7735c972877c634) }

var fileDescriptor_e7735c972877c634 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xf9, 0xff, 0xc5, 0x42, 0x47, 0x04, 0x5d, 0x3d, 0xc8, 0xb6, 0x82, 0xf4, 0xa0, 0xbd,
	0xb8, 0x4b, 0xaa, 0x37, 0x11, 0xc1, 0x83, 0x05, 0xf1, 0x94, 0xe2, 0x45, 0x04, 0x69, 0xca, 0x10,
	0x43, 0xad, 0xbb, 0xee, 0x6c, 0x02, 0x7e, 0x1d, 0x3f, 0xa9, 0x24, 0x9b, 0x5d, 0xd3, 0x60, 0xec,
	0x2d, 0x99, 0x79, 0xef, 0x37, 0x3b, 0x8f, 0x81, 0x81, 0x4e, 0x64, 0x11, 0x49, 0x42, 0x53, 0x64,
	0x0b, 0x24, 0x49, 0x9f, 0x64, 0x71, 0x25, 0xb4, 0x51, 0x56, 0xb1, 0x43, 0x8d, 0xb8, 0x9c, 0x27,
	0x4a, 0x89, 0x22, 0x12, 0x5e, 0xc2, 0x6b, 0x8b, 0x41, 0x52, 0xb9, 0x29, 0x3d, 0xa9, 0x51, 0xb9,
	0x76, 0x16, 0x3e, 0x6c, 0x37, 0x9b, 0x40, 0xce, 0xdb, 0xdd, 0x9c, 0xd0, 0xb8, 0xde, 0x88, 0xc1,
	0xde, 0x14, 0xed, 0xac, 0x92, 0xc7, 0xf8, 0x91, 0x23, 0xd9, 0xb2, 0xf6, 0x90, 0x91, 0x7d, 0x24,
	0x34, 0xe4, 0x6b, 0x77, 0xb0, 0xdf, 0xa8, 0x91, 0x56, 0xef, 0x84, 0x2c, 0x82, 0xed, 0x12, 0x45,
	0x47, 0xff, 0x4e, 0xb6, 0xc6, 0x3b, 0x93, 0x81, 0x68, 0xbe, 0x3c, 0x8c, 0x13, 0xa5, 0x29, 0x76,
	0xca, 0xd1, 0x81, 0xe3, 0x4c, 0xcb, 0xc7, 0x07, 0xf8, 0x3d, 0xb0, 0x66, 0xb1, 0xa6, 0x5f, 0x42,
	0xaf, 0xda, 0xd1, 0xe3, 0x87, 0x1d, 0xf8, 0xca, 0x16, 0xd7, 0xda, 0xc9, 0xd7, 0x7f, 0xd8, 0x75,
	0xeb, 0xcc, 0x5c, 0x74, 0x2c, 0x86, 0x7e, 0x58, 0x91, 0x9d, 0x8a, 0xdf, 0xd2, 0x15, 0xed, 0x0c,
	0xf8, 0x71, 0xc7, 0xb0, 0x1a, 0xf3, 0x0c, 0xfd, 0x10, 0x47, 0x17, 0xb3, 0x9d, 0x21, 0x3f, 0xdb,
	0xa8, 0xab, 0x37, 0x7f, 0x01, 0xf8, 0xc9, 0x83, 0xfd, 0x61, 0x5b, 0x8b, 0x91, 0x8f, 0x37, 0x0b,
	0xdd, 0x80, 0xdb, 0x9b, 0xa7, 0xeb, 0x34, 0xb3, 0xaf, 0x79, 0x22, 0x16, 0x6a, 0x25, 0xbd, 0xeb,
	0xfc, 0x6d, 0x9e, 0x50, 0xf8, 0x93, 0x7a, 0x99, 0xca, 0xf5, 0x3b, 0xbd, 0xf2, 0x1f, 0x49, 0xaf,
	0xba, 0x9e, 0x8b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x03, 0x64, 0x45, 0xc9, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemServiceClient interface {
	GetSystem(ctx context.Context, in *GetSystemRequest, opts ...grpc.CallOption) (*resources.System, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
}

type systemServiceClient struct {
	cc *grpc.ClientConn
}

func NewSystemServiceClient(cc *grpc.ClientConn) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) GetSystem(ctx context.Context, in *GetSystemRequest, opts ...grpc.CallOption) (*resources.System, error) {
	out := new(resources.System)
	err := c.cc.Invoke(ctx, "/peekaboo.v1.services.SystemService/GetSystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/peekaboo.v1.services.SystemService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/peekaboo.v1.services.SystemService/ListGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
type SystemServiceServer interface {
	GetSystem(context.Context, *GetSystemRequest) (*resources.System, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
}

// UnimplementedSystemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSystemServiceServer struct {
}

func (*UnimplementedSystemServiceServer) GetSystem(ctx context.Context, req *GetSystemRequest) (*resources.System, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystem not implemented")
}
func (*UnimplementedSystemServiceServer) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedSystemServiceServer) ListGroups(ctx context.Context, req *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroups not implemented")
}

func RegisterSystemServiceServer(s *grpc.Server, srv SystemServiceServer) {
	s.RegisterService(&_SystemService_serviceDesc, srv)
}

func _SystemService_GetSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/peekaboo.v1.services.SystemService/GetSystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetSystem(ctx, req.(*GetSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/peekaboo.v1.services.SystemService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/peekaboo.v1.services.SystemService/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SystemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "peekaboo.v1.services.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystem",
			Handler:    _SystemService_GetSystem_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _SystemService_ListUsers_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _SystemService_ListGroups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/v1/services/system.proto",
}
